### ISSUE TITLE
In Android 8.0 notification sound doesn't playing.

### ISSUE THREAD

**Issue by weiddolo** [DimitarStoyanoff/Notifications#2]
In Android 8.0 notification sound doesn't playing. Why?

**Comment by DimitarStoyanoff** [comment]
@weiddolo This is because the importance level of the notification channel in this example is set to IMPORTANCE_LOW. Notifications with default importance and above have sounds. 

Changing it to IMPORTANCE_DEFAULT will solve your issue. 

I also recommend reading about importance and setting your notifications depending on your case according to the android development standards described here:
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#importance

**Comment by weiddolo** [comment]
I've added:
![image](https://user-images.githubusercontent.com/10815675/37651594-e82b7c9e-2c38-11e8-8c0f-9c57fd85c43f.png)

![image](https://user-images.githubusercontent.com/10815675/37651639-11f7323e-2c39-11e8-8b46-403b95359563.png)

but notification sound not playing

**Comment by DimitarStoyanoff** [comment]
@weiddolo It is possible that you are accidentally using the low importance channel that you already created. Make sure you're using the right channel id. You can try reinstalling the app, and check the app settings for the channels(see if yours with the right priority is there). 
You can also try setting sounds manually by adding .setSound(...) to the channel and/or the notification builder.
